In [2]:
import numpy as np 
from sklearn.preprocessing import MinMaxScaler ,StandardScaler

# * Equation of min max 
$$MinMax =\frac{x-min}  {max-min}$$ 
***Note :  it is applied For Every Column not whole data***

In [4]:
def min_max_scaler (data) :
    data=data.astype(float)
    number_columns = data.shape[1] 
    for i in range (number_columns) :
        old_col = data[:,i]
        min_col = old_col.min()
        max_col = old_col.max()
        if max_col == min_col :
            data[:,i] = np.zeros_like(data[:,i])
            continue
            
        numerator = old_col - min_col
        denominator = max_col- min_col 
        data[:,i] = numerator / denominator
    return data
    
data = np.array([[1,100,10000,],
                [2,200,20000,],
                [3,300,30000]])


In [5]:
data

array([[    1,   100, 10000],
       [    2,   200, 20000],
       [    3,   300, 30000]])

In [6]:
min_max_scaler(data)

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

# Sklearn_MinMax Scaler

In [8]:
data = np.array([[1,100,10000,],
                [2,200,20000,],
                [3,300,30000]])

sk_min_max_scaler=MinMaxScaler()
sk_min_max_scaler.fit_transform(data)

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

# * Equation of Standard Scaler 
$$Standard Scaler =\frac{x-mean} {std}$$ 
***Note :  it is applied For Every Column not whole data***

In [10]:
def standard_scaler (data) :
    data=data.astype(float)
    number_columns = data.shape[1] 
    for i in range (number_columns) :
        old_col = data[:,i]
        mean_col = np.mean(old_col)
        std_col = np.std(old_col)
        numerator = old_col- mean_col 
        
        data[:,i] = numerator / std_col
    return data
    
data = np.array([[1,100,10000,],
                [2,200,20000,],
                [3,300,30000]])


In [11]:
standard_scaler(data)

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

# Sklearn_StandardScaler

In [13]:
data = np.array([[1,100,10000,],
                [2,200,20000,],
                [3,300,30000]])

sk_standard_scaler=StandardScaler()
sk_standard_scaler.fit_transform(data)

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])